### PR TITLE
Fixed transformRequest & transformResponse handlers

### PR DESCRIPTION
**Pull request by atnartur**
Fixed very important bug with transformation request & response. Without this fix all methods (exclude auth) was not worked normally.

### CODE REVIEW

**Comment by atnartur** [comment]
Merge this one please. It is very important bug

**Comment by boo1ean** [comment]
how did you install dependencies? this notation requires latest `apiapi` version

**Comment by boo1ean** [comment]
could you update `apiapi` version to `1.6.1` and test if it works correctly?

**Comment by atnartur** [comment]
Dependencies installed with `npm i amocrm-api`. After cloning project`s fork I use`npm i` for install modules. In [package.json](https://github.com/atnartur/node-amocrm-api/blob/fix_auth/package.json) has v1.3.0.

**Comment by boo1ean** [comment]
`apiapi@1.3.0` has `before` and `after` property names for those hooks.

Changes you introduced in this PR fit for latest `apiapi` version, but not for `1.3.0`

**Comment by atnartur** [comment]
Everything is OK. Can I commit new version on package.json file with new apiapi version?

**Comment by boo1ean** [comment]
sure

**Comment by atnartur** [comment]
Commited.

**Comment by boo1ean** [comment]
published `amocrm-api@1.3.0`

**Pull request merged**
